#!/usr/bin/php
<?php
require_once 'core/client-use.php';

class Kernel extends Cli
{
    public function start()
    {
        $this->run_cli();
    }

    public function set()
    {
        $this->set_options();
    }
}